### ISSUE TITLE
Hello World

### ISSUE THREAD

**Issue by MarkoVu12** [alptium/marko.vujicic#2]

**Comment by MarkoVu12** [comment]
@valentinacupac i've done my task.

**Comment by valentinajemuovic** [comment]
Hi @MarkoVu12, the ticket is fine, but I cannot see the "helloworld" project in your GitHub repository alptium/marko.vujicic. Please check this.

**Comment by MarkoVu12** [comment]
@valentinacupac Is it ok now? I might be wrong, but i can see it.

**Comment by valentinajemuovic** [comment]
@MarkoVu12, I got this repository https://github.com/alptium/marko.vujicic and it is not there.

**Comment by MarkoVu12** [comment]
@valentinacupac I think i got it now. Please take a look at it. Thanks

**Comment by valentinajemuovic** [comment]
@MarkoVu12, ok I can see the code, it's now on GitHub. Just to check, have you also been able to run the program (clicking on the green arrow in Eclipse, which builds and executes the program) and does it work?

**Comment by MarkoVu12** [comment]
@valentinacupac Sorry for not replaying sooner... Yes! I was getting an error, but now everything is fixed.

**Comment by valentinajemuovic** [comment]
@MarkoVu12, I didn't see this ticket because it's still In progress. You always need to move it to In review after your fixes, because I only look at tickets that are In review. I've moved it now.

**Comment by MarkoVu12** [comment]
@valentinacupac Thank you for moving it.

**Comment by valentinajemuovic** [comment]
@MarkoVu12, seems like something strange has happened, please **delete** the following because they are not in the correct Eclipse format:
Hello World
Hello World .settings

Try again based on https://github.com/alptium/valentina.cupac/wiki/03.-Hello-World where I've added more detailed steps..

**Comment by valentinajemuovic** [comment]
@MarkoVu12, please see review comment 12 in https://github.com/alptium/valentina.cupac/wiki/03.-Hello-World

**Comment by MarkoVu12** [comment]
@valentinacupac Is it ok now?

**Comment by valentinajemuovic** [comment]
@MarkoVu12:
1. Delete Hello World .settings
2. Delete Hello World/src/helloworld
3. https://github.com/alptium/marko.vujicic/blob/master/hello-world/src/helloworld/Main.java this is not the correct hello world file.
4. The project does not build nor run. Did you try to execute it before committing & pushing? Please ensure this is always done before committing.

**Comment by MarkoVu12** [comment]
@valentinacupac I deleted Hello World.settings & Hello Wolrd/src/helloworld
I did try to execute and commit before pushing.

**Comment by valentinajemuovic** [comment]
@MarkoVu12:
1. This is the current code you have for Hello World -
 is that correct? https://github.com/alptium/marko.vujicic/blob/master/hello-world/src/helloworld/Main.java
2. See https://github.com/alptium/valentina.cupac/wiki/03.-Hello-World comment 39

**Comment by MarkoVu12** [comment]
@valentinacupac Something terribly went wrong. I will work on it again and update it again! :)

**Comment by MarkoVu12** [comment]
@valentinacupac Done

**Comment by valentinajemuovic** [comment]
@MarkoVu12, correct.
